django_mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    # http://ip:port/polls/
    path('', views.index, name='index'),
    # http://ip:port/polls/index/
    path('index', views.index, name='index'),
    # http://ip:port/polls/1/
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('simple/', views.SimpleView, name='simple')
]

polls/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text


    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.template import loader
from django.urls import reverse # 类似前端模板语言url函数
from django.views import generic



# def index(request):
#     return HttpResponse("""
#     <!DOCTYPE html>
#         <html lang="en">
#             <head>
#             <meta charset="UTF-8">
#             <title>Title</title>
#             </head>
# <body>
# <h1>hello world</h1>
# </body>
# </html>""")
# def index(request):
#     """
#     展示问题列表
#     """
#     question_list = Question.objects.all().order_by('-pub_date')[0:2]
#     # print(question_list)
#     # output = ''
#     # for i in question_list:
#     #     print(i.id, i.question_text, i.pub_date)
#     #     output = output + i.question_text + ','
#     # print(output)
#     # output = ','.join([i.question_text for i in question_list])
#     template = loader.get_template('polls/index.html')
#     context = {'question_list': question_list}
#     return HttpResponse(template.render(context, request))o
def index(request):
    question_list = Question.objects.order_by('-pub_date')[:2]
    context = {'question_list': question_list}
    return render(request, 'polls/index.html', context=context)

def detail(request, question_id):
    """
    显示一个问题的详细信息，问题内容， 问题发布时间、选项内容， 每个选项的投票数
    """
    try:
        question = Question.objects.get(id=question_id)
        print(question)

        # choices = Choice.objects.filter(question=question.id)
        # 由于orm 代劳， question 直接带出对应的choices
        # choices = question.choice_set.all()
        # 由于前端模板语言本质是后端代码，可以把上句话放在HTML页面中写，有助于降低后端复杂度
    except Question.DoesNotExist:
        raise Http404("404，此ID的问题不存在")
    print(question)
    context = {
        'question': question,
    }
    return render(request, 'polls/detail.html', context)

    # 写法3：
    # question = get_object_or_404(Question, id=question_id)
    # print(question)
    # return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    """
    投票结果
    """
    question = Question.objects.get(id=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    """
    投票
    """
    try:
        question = Question.objects.get(id=question_id)
        choices = question.choice_set.all()
        choices_id = request.POST['choice']
        selected_choice = question.choice_set.get(id=choices_id)
    except Question.DoesNotExist as e:
        error_message = '问题内容不存在，检查问题id'
    except Choice.DoesNotExist as e:
        error_message = '问题的选项不存在'
        return render(request, 'polls/detail.html',context={
            'question': question,
            'error_message': error_message
        })
    else:
        # sql update choice set votes=votes+1 where id=2
        selected_choice.votes += 1
        # commit;
        selected_choice.save()
        # 投完票重定向到views.results(qid)
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    print('同九年，汝何秀')


# 通用模板示例，跟def index类比着看
class SimpleView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'question_list'

    def get_queryset(self):
        return Question.objects.all()

templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>问题详情页</title>
</head>
<body>

</body>
  <h1>{{ question.question_text }}</h1>
{#  <ul>#}
{#    {% for choice in question.choice_set.all %}#}
{#      <li>{{ choice.choice_text }}</li>#}
{#    {% endfor %}#}
{#  #}
{#  </ul>#}
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}"  method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <lable for="choice{{ forloop.counter }}">{{ choice.choice_text }}</lable>
  {% endfor %}
  <input type="submit" value="投票">
</form>


{#{% for i in choices %}#}
{#  <p>{{ i.choice_text }}</p>#}
{#{% endfor %}#}
</html>

templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>投票</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
  {% if not question_list %}
    <p>问题列表为空</p>
  {% endif %}
  <ul>
    {% for q in question_list %}
      <a href="{% url 'polls:detail' q.id %}"><li>问题：{{ q.question_text }} 发布时间：{{ q.pub_date }}</li></a>
    {% endfor %}
  </ul>
</body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>结果页</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
  <ul>
    {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}</li>
    {% endfor %}
  </ul>

</body>
</html>